language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
    - wget https://www.w3.org/2009/XMLSchema/derived.nxsd https://www.w3.org/2009/XMLSchema/XMLSchema.xsd
    - cargo test
    - cargo run --bin gen derived.nxsd XMLSchema.xsd > foo.rs
    - diff foo.rs src/parser.rs # Fails if they are different.
